import json
import datetime
import random
from agents.scout_agent import ScoutAgent
from agents.strategist_agent import StrategistAgent
from agents.visualizer_agent import VisualizerAgent
from agents.banter_agent import BanterAgent

class ReportGenerator:
    def __init__(self):
        self.scout = ScoutAgent()
        self.strategist = StrategistAgent()
        self.visualizer = VisualizerAgent()
        self.banter = BanterAgent()
        self.tactical_lib_path = "data/tactical_library.md"

    def get_chapter_wisdom(self, chapter_num):
        """Extracts a specific chapter from the tactical library."""
        try:
            with open(self.tactical_lib_path, 'r', encoding='utf-8') as f:
                content = f.read()
                # Simple logic to split by double hash headers
                chapters = content.split("## ")
                for ch in chapters:
                    if ch.startswith(str(chapter_num)):
                        return "## " + ch.strip()
        except FileNotFoundError:
            return "Tactical Library not found in armory."
        return "Wisdom currently obscured by the fog of war."

    def create_victory_plan(self, user_issue):
        # 1. Intelligence Gathering
        intel = self.scout.conduct_reconnaissance(user_issue)
        
        # 2. Strategy Selection (Mapping 1-13)
        # For complexity, we map specific domains to chapters
        mapping = {"financial": 2, "social": 3, "internal": 1, "relational": 13}
        target_ch = mapping.get(intel['domain'], random.randint(1, 13))
        
        # 3. Assemble the Components
        plan = self.strategist.formulate_plan(intel)
        wisdom = self.get_chapter_wisdom(target_ch)
        visual = self.visualizer.generate_mermaid(plan)
        joke = self.banter.crack_joke()

        # 4. Format the Markdown Report
        report = f"""
# 📜 Sun Tzu_Easy_Life: Victory Plan
**Timestamp:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}
**Strategic Theater:** {intel['domain'].upper()}
**Urgency Level:** {intel['urgency']}

---

## 🧠 The Scout's Intelligence Report
> "{intel['intel']}"

## 🛡️ Core Strategy: Chapter {target_ch}
{wisdom}

## ⚡ The Execution (The General's Orders)
- **Primary Maneuver:** {plan['maneuver']}
- **Warning:** {plan['warning']}

## 📊 Visual Battle Map
{visual}

---

## 🍵 A Moment of Zen (Banter)
*{joke}*

---
*Generated by the Sun Tzu_Easy_Life Framework.*
"""
        return report

if __name__ == "__main__":
    # Example Execution
    generator = ReportGenerator()
    user_problem = "I am overwhelmed by debt and office drama."
    print(generator.create_victory_plan(user_problem))
